
service: react-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5000

functions:
  index:
    handler: handler.index
    events:
      - httpApi:
          path: /
          method: get
  predict:
    handler: predict.model
    events:
      - httpApi:
          path: /model
          method: post